spring:
  application:
    name: eureka_server_maven
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8887/eureka
    healthcheck:
      enabled: true    

logging:
  level:
    com:
      netflix:
        eureka:OFF
        discovery:OFF
        
management:
  security:
    enabled: false        
https://piotrminkowski.wordpress.com/2018/05/21/secure-discovery-with-spring-cloud-netflix-eureka/
--- 
spring:
  profiles: default
server:
  port: 8887  
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-store-password: 50981234
    trust-store: classpath:eureka.jks
    trust-store-password: 50981234
    key-alias: eureka
    client-auth: need